import { IContact } from "../contact/contact";
import { IModelPiercing } from "../piercing/modelPiercing";
import { IPhoto } from "../photo/photo";
import { IVideo } from "../video/video";
import { IBlockedCountry } from "../blockedCountry/blockedCountry";
import { ITarif } from "../tarif/tarif";
import { IWorkTime } from "../workTime/workTime";
import { IModelService } from "../modelService/modelService";
import { IModelLanguage } from "../language/modelLanguage";
import { IModelFeedback } from "../modelFeedback/modelFeedback";
import { IModelProposalPlace } from "../modelProposalPlace/modelProposalPlace";

export interface IModel {
  id: number;
  agency_id: number;
  name: string;
  about_self: string;
  age: number;
  type_id: number;
  height: number;
  weight: number;
  country_id: number;
  city_id: number;
  district_id: number;
  underground_id: number;
  orientation_id: number;
  meeting_id: number;
  ethnic_group_id: number;
  hair_color_id: number;
  hair_size_id: number;
  breast_size_id: number;
  breast_type_id: number;
  meeting_place_id: number;
  nationality_id: number;
  trip_id: number;
  tatoo_id: number;
  smooker_id: number;
  eyes_color_id: number;
  pubis_hair_id: number;
  contacts: IContact[];
  photos: IPhoto[];
  videos: IVideo[];
  model_piercings: IModelPiercing[];
  blocked_countries: IBlockedCountry[];
  model_languages: IModelLanguage[];
  is_vip: boolean;
  is_pornstar: number;
  is_enable: boolean;
  is_enable_by_moderator: boolean;
  currency_id: number;
  tarifs: ITarif[];
  time_zone: number;
  work_times: IWorkTime[];
  model_services: IModelService[];
  last_online: Date;
  is_verified: boolean;
  create_date: Date;
  is_payed: boolean;
  last_position_update: Date;
  model_feedbacks: IModelFeedback[];
  model_proposal_places: IModelProposalPlace[];
  positionsUpLeft: number;
}
